before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  -
    id: porkbun-ddns
    name: porkbun-ddns
    publish: true
    summary: Keep your Porkbun DNS records updated with your current IP address
    description: |
      This project updates your DNS records at Porkbun with your current public IP address.
      Your IP address is determined using https://wtfismyip.com/
      Place your configuration at `/var/snap/porkbun-ddns/common/config.yaml` and restart the service `snap restart porkbun-ddns`
    channel_templates:
      - stable
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    apps:
      porkbun-ddns:
        command: porkbun-ddns
        daemon: simple
        args: -config $SNAP_COMMON/config.yaml
        plugs: ["network"]
