version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mipsle
      - mips64le
      - riscv64
      - ppc64
      - ppc64le
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}} -X main.BuiltBy=goreleaser'

archives:
  - formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  - id: porkbun-ddns
    name: porkbun-ddns
    publish: true
    summary: Keep your Porkbun DNS records updated with your current IP address
    description: |
      This project updates your DNS records at Porkbun with your current public IP address.
      Your IP address is determined using https://wtfismyip.com/
      Place your configuration at `/var/snap/porkbun-ddns/common/config.yaml` and restart the service `snap restart porkbun-ddns.porkbun-ddns-daemon`
    channel_templates:
      - stable
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    apps:
      porkbun-ddns-daemon:
        command: porkbun-ddns
        daemon: simple
        args: -config $SNAP_COMMON/config.yaml
        plugs: [ "network" , "network-bind" ]
      porkbun-ddns:
        command: porkbun-ddns
        plugs: [ "network", "home" , "removable-media", "network-bind" ]

nfpms:
  -
    id: porkbun-ddns
    package_name: porkbun-ddns
    homepage: https://github.com/jadolg/porkbun-ddns
    maintainer: Jorge Alberto Díaz Orozco (Akiel) <diazorozcoj@gmail.com>
    description: |-
      Keep your Porkbun DNS records updated with your current IP address
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    priority: optional
    scripts:
      postinstall: ./packaging/postinstall.sh
      preremove: ./packaging/preremove.sh
    contents:
      - src: ./config.yaml
        dst: /etc/porkbun-ddns/config.yaml
        type: config|noreplace
        file_info:
          mode: 0600
      - src: ./packaging/porkbun-ddns.service
        dst: /etc/systemd/system/porkbun-ddns.service
        file_info:
          mode: 0600
