name: Go
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  goreleaser:
    name: test goreleaser build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.1.2
      with:
        cosign-release: v2.6.3

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --snapshot --clean --skip=publish,snapcraft
